In [65]:
import pandas as pd
from IPython.display import display

In [69]:
column_names = ["NUMERO_DE_RASTREO", "TIPO_DE_IDENTIFICACION_DEL_TITULAR", "NRO_DE_IDENTIFICACION_DEL_TITULAR", "INDICADOR_DE_SOLO_TITULAR_PRINCIPAL", "INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS",
"OFICINA_DUENA_DE_LA_CUENTA", "CUENTA_PERMITE_DEBITOS_SOBREGIRO", "CUENTA_PERMITE_CREDITOS_SOBREGIRO", "MARCAS_DE_LAS_CUENTAS", "FILLER_PARA_USO_FUTURO", "CODIGO_DE_RESPUESTA","DESCRIPCION_DE_RESPUESTA",
"CONSECUTIVO_DE_CUENTAS_CONSULTADAS_POR_CLIENTE","TIPO_DE_CUENTA_A_CONSULTAR", "NUMERO_DE_CUENTA","CODIGO_DE_LA_OFICINA_DUENA_DE_LA_CUENTA", "CUENTA_PERMITE_DEBITOS", "CUENTA_PERMITE_CREDITOS", "MONEDA", 
"FECHA_DE_APERTURA_DE_LA_CUENTA", "NUMERO_DE_DIAS_DE_INACTIVIDAD_DE_LA_CUENTA", "INDICADOR_DE_CUENTA_CANCELADA", "FECHA_DE_CIERRE_DE_LA_CUENTA","NUMERO_DE_COTITULARES", "TIPO_IDENTIFICACION_TITULAR", "NRO_DE_IDENTIFICACION_TITULAR",
"NOMBRE_TITULAR_CUENTA", "RELACION_ENTRE_CLIENTE_Y_CUENTA", "REGIMEN_CUENTA_MAESTRA", "CODIGO_DE_SERVICIO","PLAZO_SOBREGIRO", "DIAS_SOBREGIRO",
"DIAS_EN_MORA_SOBREGIRO", "CLASIFICACION_CARTERA_PARA_CTAS_CORRIENTES", "SIGNO_DEL_CUPO_DE_SOBREGIRO", "VALOR_DEL_CUPO_DE_SOBREGIRO", "SIGNO_DEL_SALDO_EFECTIVO_DE_LA_CUENTA",
"SALDO_EFECTIVO_DE_LA_CUENTA", "SIGNO_DEL_SALDO_EN_CANJE_DE_LA_CUENTA", "SALDO_EN_CANJE_DE_LA_CUENTA",
"SIGNO_DEL_SALDO_DISPONIBLE_DE_LA_CUENTA", "SALDO_DISPONIBLE_DE_LA_CUENTA", "SIGNO_DEL_SALDO_DISPONIBLE_SIN_SOBREGIRO", "SALDO_DISPONIBLE_SIN_SOBREGIRO", "SIGNO_DEL_SALDO_EN_CUENTA_POR_COBRAR",
"SALDO_EN_CUENTA_POR_COBRAR", "SIGNO_DEL_SALDO_BLOQUEADO", "SALDO_BLOQUEADO", "SIGNO_DE_SALDO_EN_BOLSILLOS", "SALDO_EN_BOLSILLOS", "SIGNO_DEL_SALDO_EN_CANJE_AL_INICIO_DEL_DIA", "SALDO_EN_CANJE_AL_INICIO_DEL_DIA",
"SIGNO_DEL_SALDO_EFECTIVO_AL_INICIO_DEL_DIA", "SALDO_EFECTIVO_AL_INICIO_DEL_DIA", "SIGNO_DEL_SALDO_DE_DISPONIBLE_DEL_CUPO_DE_SOBREGIRO", "SALDO_DE_DISPONIBLE_DEL_CUPO_DE_SOBREGIRO",
"SIGNO_INTERES_NORMALES", "INTERES_NORMALES", " SIGNO_INTERES_EN_SUSPENSION", "INTERES_EN_SUSPENSION", "SIGNO_CUPO_DE_REMESAS", "CUPO_DE_REMESAS", "SIGNO_CUPO_REMESA_NEGOCIADA", "CUPO_REMESA_NEGOCIADA",
"SIGNO_UTILIZACION_REMESAS", "UTILIZACION_REMESAS", "UTILIZACION_DE_REMESAS", "PARA_USO_FUTURO_INFO_DE_LA_CUENTA", "CAPTACION"
]
# import collections
# print([item for item, count in collections.Counter(column_names).items() if count > 1])

print(len(column_names))

df_productos_legales = pd.read_csv("ProductosLegales", sep="|", header=None, names=column_names, index_col=False)
display(df_productos_legales)
df_productos_legales[["NUMERO_DE_RASTREO"]]

69

/var/folders/sc/_jqd0m8s5f9gqbgm5k_1twjc0000gn/T/ipykernel_31035/4281289387.py:19: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df_productos_legales = pd.read_csv("ProductosLegales", sep="|", header=None, names=column_names, index_col=False)

,NUMERO_DE_RASTREO,TIPO_DE_IDENTIFICACION_DEL_TITULAR,NRO_DE_IDENTIFICACION_DEL_TITULAR,INDICADOR_DE_SOLO_TITULAR_PRINCIPAL,INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS,OFICINA_DUENA_DE_LA_CUENTA,CUENTA_PERMITE_DEBITOS_SOBREGIRO,CUENTA_PERMITE_CREDITOS_SOBREGIRO,MARCAS_DE_LAS_CUENTAS,FILLER_PARA_USO_FUTURO,...,INTERES_EN_SUSPENSION,SIGNO_CUPO_DE_REMESAS,CUPO_DE_REMESAS,SIGNO_CUPO_REMESA_NEGOCIADA,CUPO_REMESA_NEGOCIADA,SIGNO_UTILIZACION_REMESAS,UTILIZACION_REMESAS,UTILIZACION_DE_REMESAS,PARA_USO_FUTURO_INFO_DE_LA_CUENTA,CAPTACION
0,1,1,68287066,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
1,21,1,8699669,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
2,2,1,1090407176,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
3,40,1,80431468,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
4,23,1,75070484,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33277,9025,1,45526350,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
33278,9029,1,45485857,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
33279,9030,1,1143353738,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
33280,9030,1,1143353738,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
33281,9030,1,1143353738,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0

       NUMERO_DE_RASTREO
0                      1
1                     21
2                      2
3                     40
4                     23
...                  ...
33277               9025
33278               9029
33279               9030
33280               9030
33281               9030

[33282 rows x 1 columns]

In [18]:
df_productos_legales.describe()

,NUMERO_DE_RASTREO,TIPO_DE_IDENTIFICACION_DEL_TITULAR,INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS,OFICINA_DUENA_DE_LA_CUENTA,CUENTA_PERMITE_DEBITOS_SOBREGIRO,CUENTA_PERMITE_CREDITOS_SOBREGIRO,MARCAS_DE_LAS_CUENTAS,DESCRIPCION_DE_RESPUESTA,TIPO_DE_CUENTA_A_CONSULTAR,NUMERO_DE_CUENTA,...,SALDO_EN_CANJE_AL_INICIO_DEL_DIA,SALDO_EFECTIVO_AL_INICIO_DEL_DIA,SALDO_DE_DISPONIBLE_DEL_CUPO_DE_SOBREGIRO,INTERES_NORMALES,INTERES_EN_SUSPENSION,CUPO_DE_REMESAS,CUPO_REMESA_NEGOCIADA,UTILIZACION_REMESAS,PARA_USO_FUTURO_INFO_DE_LA_CUENTA,CAPTACION
count,33282.000000,3.328200e+04,0.0,0.0,0.0,0.0,0.0,33282.000000,3.328200e+04,33282.000000,...,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,0.0
mean,2.486028,7.605352e+08,NaN,NaN,NaN,NaN,NaN,306.944324,4.297144e+10,427.549096,...,1.123233e+09,9.983197e+11,1.448018e+11,1.448018e+11,8.345137e+06,2.976095e+07,1.608046e+13,1.661258e+12,8.006505e+10,NaN
std,0.873956,3.275985e+08,NaN,NaN,NaN,NaN,NaN,306.410109,2.947636e+10,290.686088,...,4.726736e+10,4.229484e+13,8.298614e+12,8.298614e+12,4.814788e+08,3.692825e+09,5.800174e+14,1.109346e+14,1.032824e+13,NaN
min,1.000000,2.814850e+05,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000e+08,1.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
25%,1.000000,8.909039e+08,NaN,NaN,NaN,NaN,NaN,2.000000,1.530000e+10,177.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
50%,3.000000,8.909039e+08,NaN,NaN,NaN,NaN,NaN,228.000000,4.120000e+10,373.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
75%,3.000000,8.909039e+08,NaN,NaN,NaN,NaN,NaN,575.000000,6.810000e+10,681.000000,...,0.000000e+00,1.000000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
max,3.000000,1.235244e+09,NaN,NaN,NaN,NaN,NaN,921.000000,9.979012e+10,996.000000,...,5.936188e+12,6.033467e+15,9.400000e+14,9.400000e+14,4.828117e+10,4.760949e+11,3.000000e+16,8.000000e+15,1.332362e+15,NaN

In [20]:
df_productos_legales.shape

(33282, 69)

In [21]:
total_null = df_productos_legales.isnull().sum().sort_values(ascending = False) # Total de nulos
percent_null = (df_productos_legales.isnull().sum()/df_productos_legales.isnull().count()).sort_values(ascending = False) #porcentaje de nulos
missing_data = pd.concat([total_null,percent_null],axis = 1,keys=['total_null','percent_null'])
missing_data

                                            total_null  percent_null
CAPTACION                                        33282           1.0
INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS           33282           1.0
OFICINA_DUENA_DE_LA_CUENTA                       33282           1.0
CUENTA_PERMITE_DEBITOS_SOBREGIRO                 33282           1.0
CUENTA_PERMITE_CREDITOS_SOBREGIRO                33282           1.0
...                                                ...           ...
DIAS_EN_MORA_SOBREGIRO                               0           0.0
CLASIFICACION_CARTERA_PARA_CTAS_CORRIENTES           0           0.0
TIPO_DE_IDENTIFICACION_DEL_TITULAR                   0           0.0
VALOR_DEL_CUPO_DE_SOBREGIRO                          0           0.0
SIGNO_DEL_CUPO_DE_SOBREGIRO                          0           0.0

[69 rows x 2 columns]

In [22]:
df_productos_legales.dtypes

NUMERO_DE_RASTREO                           int64
TIPO_DE_IDENTIFICACION_DEL_TITULAR          int64
NRO_DE_IDENTIFICACION_DEL_TITULAR          object
INDICADOR_DE_SOLO_TITULAR_PRINCIPAL        object
INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS    float64
                                           ...
SIGNO_UTILIZACION_REMESAS                  object
UTILIZACION_REMESAS                         int64
UTILIZACION_DE_REMESAS                     object
PARA_USO_FUTURO_INFO_DE_LA_CUENTA           int64
CAPTACION                                 float64
Length: 69, dtype: object

In [57]:
df_productos_virtuales = pd.read_csv("ProductosVirtuales", sep="|", header=None, names=column_names)
# df_productos_virtuales = pd.read_csv("ProductosVirtuales", sep="|", header=None)
df_productos_virtuales.head()

,NUMERO_DE_RASTREO,TIPO_DE_IDENTIFICACION_DEL_TITULAR,NRO_DE_IDENTIFICACION_DEL_TITULAR,INDICADOR_DE_SOLO_TITULAR_PRINCIPAL,INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS,OFICINA_DUENA_DE_LA_CUENTA,CUENTA_PERMITE_DEBITOS_SOBREGIRO,CUENTA_PERMITE_CREDITOS_SOBREGIRO,MARCAS_DE_LAS_CUENTAS,FILLER_PARA_USO_FUTURO,...,INTERES_EN_SUSPENSION,SIGNO_CUPO_DE_REMESAS,CUPO_DE_REMESAS,SIGNO_CUPO_REMESA_NEGOCIADA,CUPO_REMESA_NEGOCIADA,SIGNO_UTILIZACION_REMESAS,UTILIZACION_REMESAS,UTILIZACION_DE_REMESAS,PARA_USO_FUTURO_INFO_DE_LA_CUENTA,CAPTACION
0,1,3,890900250,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
1,307,2,59152459,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
2,307,3,19091109214037,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
3,205,7,219030612,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0
4,69,5,5059152464,T,Y,NaN,NaN,NaN,NaN,NaN,...,+,0,+,0,+,0,+,0,+,0

In [58]:
total_null = df_productos_virtuales.isnull().sum().sort_values(ascending = False) # Total de nulos
percent_null = (df_productos_virtuales.isnull().sum()/df_productos_virtuales.isnull().count()).sort_values(ascending = False) #porcentaje de nulos
missing_data = pd.concat([total_null,percent_null],axis = 1,keys=['total_null','percent_null'])
missing_data

                                            total_null  percent_null
OFICINA_DUENA_DE_LA_CUENTA                         928           1.0
CUENTA_PERMITE_DEBITOS_SOBREGIRO                   928           1.0
CUENTA_PERMITE_CREDITOS_SOBREGIRO                  928           1.0
MARCAS_DE_LAS_CUENTAS                              928           1.0
FILLER_PARA_USO_FUTURO                             928           1.0
...                                                ...           ...
DIAS_EN_MORA_SOBREGIRO                               0           0.0
CLASIFICACION_CARTERA_PARA_CTAS_CORRIENTES           0           0.0
TIPO_DE_IDENTIFICACION_DEL_TITULAR                   0           0.0
VALOR_DEL_CUPO_DE_SOBREGIRO                          0           0.0
CAPTACION                                            0           0.0

[69 rows x 2 columns]

In [59]:
df_productos_virtuales.dtypes

NUMERO_DE_RASTREO                          int64
TIPO_DE_IDENTIFICACION_DEL_TITULAR         int64
NRO_DE_IDENTIFICACION_DEL_TITULAR          int64
INDICADOR_DE_SOLO_TITULAR_PRINCIPAL       object
INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS    object
                                           ...
SIGNO_UTILIZACION_REMESAS                  int64
UTILIZACION_REMESAS                       object
UTILIZACION_DE_REMESAS                     int64
PARA_USO_FUTURO_INFO_DE_LA_CUENTA         object
CAPTACION                                  int64
Length: 69, dtype: object

In [60]:
df_productos_legales.describe()

,NUMERO_DE_RASTREO,TIPO_DE_IDENTIFICACION_DEL_TITULAR,INDICADOR_DE_OMITIR_CUENTAS_CANCELADAS,OFICINA_DUENA_DE_LA_CUENTA,CUENTA_PERMITE_DEBITOS_SOBREGIRO,CUENTA_PERMITE_CREDITOS_SOBREGIRO,MARCAS_DE_LAS_CUENTAS,DESCRIPCION_DE_RESPUESTA,TIPO_DE_CUENTA_A_CONSULTAR,NUMERO_DE_CUENTA,...,SALDO_EN_CANJE_AL_INICIO_DEL_DIA,SALDO_EFECTIVO_AL_INICIO_DEL_DIA,SALDO_DE_DISPONIBLE_DEL_CUPO_DE_SOBREGIRO,INTERES_NORMALES,INTERES_EN_SUSPENSION,CUPO_DE_REMESAS,CUPO_REMESA_NEGOCIADA,UTILIZACION_REMESAS,PARA_USO_FUTURO_INFO_DE_LA_CUENTA,CAPTACION
count,33282.000000,3.328200e+04,0.0,0.0,0.0,0.0,0.0,33282.000000,3.328200e+04,33282.000000,...,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,3.328200e+04,0.0
mean,2.486028,7.605352e+08,NaN,NaN,NaN,NaN,NaN,306.944324,4.297144e+10,427.549096,...,1.123233e+09,9.983197e+11,1.448018e+11,1.448018e+11,8.345137e+06,2.976095e+07,1.608046e+13,1.661258e+12,8.006505e+10,NaN
std,0.873956,3.275985e+08,NaN,NaN,NaN,NaN,NaN,306.410109,2.947636e+10,290.686088,...,4.726736e+10,4.229484e+13,8.298614e+12,8.298614e+12,4.814788e+08,3.692825e+09,5.800174e+14,1.109346e+14,1.032824e+13,NaN
min,1.000000,2.814850e+05,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000e+08,1.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
25%,1.000000,8.909039e+08,NaN,NaN,NaN,NaN,NaN,2.000000,1.530000e+10,177.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
50%,3.000000,8.909039e+08,NaN,NaN,NaN,NaN,NaN,228.000000,4.120000e+10,373.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
75%,3.000000,8.909039e+08,NaN,NaN,NaN,NaN,NaN,575.000000,6.810000e+10,681.000000,...,0.000000e+00,1.000000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
max,3.000000,1.235244e+09,NaN,NaN,NaN,NaN,NaN,921.000000,9.979012e+10,996.000000,...,5.936188e+12,6.033467e+15,9.400000e+14,9.400000e+14,4.828117e+10,4.760949e+11,3.000000e+16,8.000000e+15,1.332362e+15,NaN